apiVersion: v1
kind: ReplicationController
metadata:
  name: mynginx-rc
spec:
   replicas: 2
   selector:
     app:  mynginx
   template:
     metadata:
      labels:
        app:  mynginx
        
     spec:
       containers:
        - name: myjavaappcontianer
          image: maha4iac/myonlinebooking:2
          ports:
          - containerPort: 8080